user/urls.py
from django.urls import path
import user.views as userviews

app_name = 'user'

urlpatterns = [
    path('', userviews.HomeView.as_view(), name='home'),
    path(
        'api/register/',
        userviews.RegisterAPIView.as_view(),
        name='api-register'
    ),
    path(
        'register_user/',
        userviews.RegisterFormView.as_view(),
        name='form-register'
    ),
    path(
        'api/list_users/',
        userviews.ListUsersAPIView.as_view(),
        name='list-users-api'
    ),
    path('list_users/', userviews.user_list_view, name='list-users'),
]

userapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import ( 
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path(
        'api-auth/', include('rest_framework.urls', namespace='rest_framework')
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.MEDIA_URL, document_root=settings.UPLOAD_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager


class ProfileManager(UserManager):
	def create(self, *args, **kwargs):
		user = UserProfile(*args, **kwargs)
		user.password = make_password(user.password)
		user.save()
		return user


class UserProfile(AbstractUser):
    """Extension to the default User model.
    
    The only additional field is photo Image field
    """
    
    email = models.EmailField(
    	unique=True, blank=False, max_length=254, verbose_name='email address'
    )
    photo = models.ImageField(upload_to='uploads/', blank=True)
    objects = ProfileManager()

user/forms.py
from crispy_forms import layout
from crispy_forms.helper import FormHelper
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django import forms
from .models import UserProfile


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Username', max_length=45)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
        min_length=settings.MIN_PASSWORD_LENGTH,
        label='Password',
        strip=False,
        help_text=f'Enter {settings.MIN_PASSWORD_LENGTH} digits and chars',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        min_length=settings.MIN_PASSWORD_LENGTH,
        label='Repeat the password',
        strip=False,
        widget=forms.PasswordInput()
    )
    photo = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            'photo'
        )

    def crispy_init(self):
        """Initialize crispy-forms helper."""
        self.helper = FormHelper()
        self.helper.form_id = 'id-RegistrationForm'
        self.helper.form_class = 'form-group'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse_lazy('user:api-register')

        self.helper.layout = layout.Layout(
            layout.Field('username'),
            layout.Field('email'),
            layout.Field('password1'),
            layout.Field('password2'),
            layout.Field('photo'),
            layout.Div(
                layout.Submit(
                    'submit',
                    'Register',
                    css_class='btn-success my-2 px-4'
                ),
                css_class='text-center'
            )
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.crispy_init()

user/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormView
from rest_framework import generics, permissions, filters
from rest_framework.decorators import api_view, permission_classes
from rest_framework.parsers import JSONParser, MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import status

from .forms import RegisterForm
from .models import UserProfile
from .serializers import UserSerializer


class HomeView(generic.TemplateView):
    template_name = "html/base.html"


class RegisterAPIView(generics.CreateAPIView):
    """POST /api/register/."""

    permission_classes = (permissions.AllowAny,)
    serializer_class = UserSerializer
    parser_classes = [MultiPartParser, JSONParser]

    def init_from_dict(self, data: dict, photo=None):
        self.username = data.get('username')
        self.email = data.get('email')
        self.password = data.get('password1')
        self.password2 = data.get('password2')
        if photo is not None:
            self.photo = photo
        else:
            self.photo = data.get('photo')

    def post(self, request, *args, **kwargs):
        if len(request.POST) > 1:
            form = RegisterForm(request.POST)
            if form.is_valid():
                photo = request.FILES.get('photo')
                self.init_from_dict(request.POST, photo=photo)
            else:
                return render(request, 'html/register.html', {'form': form})
        else:
            self.init_from_dict(request.data)

        new_user = UserProfile.objects.create(
            username=self.username,
            email=self.email,
            password=self.password,
            photo=self.photo
        )
        return Response({
            'data': UserSerializer(new_user).data,
            'status': status.HTTP_201_CREATED
        })


class RegisterFormView(FormView):
    """GET /register_user/."""

    form_class = RegisterForm
    template_name = 'html/register.html'
    success_url = reverse_lazy('user:home')


class ListUsersAPIView(generics.ListAPIView):
    """GET list_users/."""

    queryset = UserProfile.objects.all()
    serializer_class = UserSerializer
    permission_classes = (permissions.IsAuthenticated,)
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ['username', 'email']


def add_orderings(qs: QuerySet, orderings: str) -> QuerySet:
    orderings = orderings.split(',')
    qs = qs.order_by(*orderings)
    return qs


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def user_list_view(request):
    qs = UserProfile.objects.only(
        'id', 'username', 'email', 'photo'
    )

    if orderings := request.GET.get('ordering'):
        qs = add_orderings(qs, orderings)

    data = []
    for profile in list(qs):
        data.append({
            'id': profile.id,
            'username': profile.username,
            'email': profile.email,
            'photo': profile.photo
        })

    return render(request, 'html/list_users.html', {'data': data})

templates/html/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    
    <!-- Third-party styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha512-rO2SXEKBSICa/AfyhEK5ZqWFCOok1rcgPYfGOqtX35OyiraBg6Xa4NnBJwXgpIRoXeWjcAmcQniMhp22htDc6g==" crossorigin="anonymous" />
    <!-- Extra styles -->
    {% block extra_css %}{% endblock extra_css %}

    <!-- Third-party js -->
    <script defer src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha512-Oy5BruJdE3gP9+LMJ11kC5nErkh3p4Y0GawT1Jrcez4RTDxODf3M/KP3pEsgeOYxWejqy2SPnj+QMpgtvhDciQ==" crossorigin="anonymous"></script>
    <!-- Extra js -->
    {% block extra_js %}{% endblock extra_js %}
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'user:home' %}">Craft Group Assignment</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        List users <span class="sr-only">(current)</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'user:list-users-api' %}">API</a>
                        <a class="dropdown-item" href="{% url 'user:list-users' %}">HTML</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Authentication
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'user:form-register' %}">Register</a>
                        <a class="dropdown-item" href="{% url 'rest_framework:login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'rest_framework:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'rest_framework:logout' %}" class="btn btn-light px-4">Logout</a>
                    {% else %}
                    <a href="{% url 'rest_framework:login' %}" class="btn btn-light px-4">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% endblock navbar %}
    {% block content %}{% endblock content %}
</body>

</html>

templates/html/list_users.html
{% extends "html/base.html" %}

{% block content %}
    <div class="container mx-auto my-5 text-center col-6">
        <h4 class="text-center">User list</h4>
        <div id="response" class="text-left bg-light pt-5">
            <div class="dropdown text-right">
              <button class="btn btn-primary dropdown-toggle mx-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Change ordering</button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'user:list-users' %}?ordering=email">Email ASC</a>
                    <a class="dropdown-item" href="{% url 'user:list-users' %}?ordering=-email">Email DESC</a>
                    <a class="dropdown-item" href="{% url 'user:list-users' %}?ordering=username">Username ASC</a>
                    <a class="dropdown-item" href="{% url 'user:list-users' %}?ordering=-username">Username DESC</a>
              </div>
            </div>
            <div class="container">
                {% for user in data %}
                    <p>User {{ user.id }}:</p>
                    <p>username: {{ user.username }}</p>
                    <p>email: {{ user.email }}</p>
                    {% if user.photo %}
                        <div class="col-5 p-0">
                            <img class="img-fluid img-thumbnail" src="/{{ user.photo.name }}">
                        </div>
                    {% else %}
                        <p>No photo available</p><br>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/html/register.html
{% extends 'html/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Register{% endblock title %}
{% block content %}
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <div class="container my-5">
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock content %}